library(SNPfiltR)
library(vcfR)

path_vcf<-"/storage1/fs1/christine.e.edwards/Active/aguirre/boltonia/subset_data/LD_pruned_vcf/"

for(i in 1:9){
path_vcf_i <-paste0(path_vcf,"Boltonia_Chr_",i,"_full_merged_subsetted_LD_pruned.vcf.gz")
vcfR_i <- read.vcfR(path_vcf_i)
#keep biallelic SNPs
vcfR_i <- filter_biallelic(vcfR_i)
#execute allele balance filter 0.25 and 0.75
#vcfR_i<-filter_allele_balance(vcfR_i)
#allele depth is not specified in input vcf in 'AD' or 'CATG' format, therefore allele balance cannot be calculated
#remove invariant sites generated by dropping individuals
vcfR_i <- missing_by_snp(vcfR_i, cutoff = 0.95)
# filter minor allele count (must have only biallelic loci)
vcfR_i<-min_mac(vcfR_i, min.mac = 1)
write.vcf(vcfR_i,paste0(path_vcf,"Boltonia_Chr_",i,"_SNPfiltr_usnps.vcf.gz"))
}
